export const partyTrailSignals: any;
export const partyStream: any;
export const trailStream: any;
export const followerCountStream: any;
export const updatePartyValue: (value: any, options?: any) => void;
export const updateTrailValue: (value: any, options?: any) => void;
export const updateFollowerCountValue: (value: any, options?: any) => void;
export const getPartyValue: <T>(fallback: T, options?: any) => T;
export const getTrailValue: <T>(fallback: T, options?: any) => T;
export const getFollowerCountValue: (fallback: number, options?: any) => number;
